CC=javac

P1=UdpCliBcast
P2=UdpCli
P3=UdpCliTo
P4=UdpSrv
P5=UdpSrvMport

all: $(P1).class $(P2).class $(P3).class $(P3).class $(P4).class $(P5).class

$(P1).class: $(P1).java
	$(CC) $(P1).java

$(P2).class: $(P2).java
	$(CC) $(P2).java

$(P3).class: $(P3).java
	$(CC) $(P3).java

$(P4).class: $(P4).java
	$(CC) $(P4).java

$(P5).class: $(P5).java
	$(CC) $(P5).java

clean:
	rm -f *.class

